export { stateFipsMap };

const stateFipsMap = {
  1: { stateAbbr: "AL", stateName: "Alabama", mcd: false },
  2: { stateAbbr: "AK", stateName: "Alaska", mcd: false },
  4: { stateAbbr: "AZ", stateName: "Arizona", mcd: false },
  5: { stateAbbr: "AR", stateName: "Arkansas", mcd: false },
  6: { stateAbbr: "CA", stateName: "California", mcd: false },
  8: { stateAbbr: "CO", stateName: "Colorado", mcd: false },
  9: { stateAbbr: "CT", stateName: "Connecticut", mcd: true },
  10: { stateAbbr: "DE", stateName: "Delaware", mcd: false },
  11: { stateAbbr: "DC", stateName: "District of Columbia", mcd: false },
  12: { stateAbbr: "FL", stateName: "Florida", mcd: false },
  13: { stateAbbr: "GA", stateName: "Georgia", mcd: false },
  15: { stateAbbr: "HI", stateName: "Hawaii", mcd: false },
  16: { stateAbbr: "ID", stateName: "Idaho", mcd: false },
  17: { stateAbbr: "IL", stateName: "Illinois", mcd: false },
  18: { stateAbbr: "IN", stateName: "Indiana", mcd: false },
  19: { stateAbbr: "IA", stateName: "Iowa", mcd: false },
  20: { stateAbbr: "KS", stateName: "Kansas", mcd: false },
  21: { stateAbbr: "KY", stateName: "Kentucky", mcd: false },
  22: { stateAbbr: "LA", stateName: "Louisiana", mcd: false },
  23: { stateAbbr: "ME", stateName: "Maine", mcd: true },
  24: { stateAbbr: "MD", stateName: "Maryland", mcd: false },
  25: { stateAbbr: "MA", stateName: "Massachusetts", mcd: true },
  26: { stateAbbr: "MI", stateName: "Michigan", mcd: true },
  27: { stateAbbr: "MN", stateName: "Minnesota", mcd: true },
  28: { stateAbbr: "MS", stateName: "Mississippi", mcd: false },
  29: { stateAbbr: "MO", stateName: "Missouri", mcd: false },
  30: { stateAbbr: "MT", stateName: "Montana", mcd: false },
  31: { stateAbbr: "NE", stateName: "Nebraska", mcd: false },
  32: { stateAbbr: "NV", stateName: "Nevada", mcd: false },
  33: { stateAbbr: "NH", stateName: "New Hampshire", mcd: true },
  34: { stateAbbr: "NJ", stateName: "New Jersey", mcd: true },
  35: { stateAbbr: "NM", stateName: "New Mexico", mcd: false },
  36: { stateAbbr: "NY", stateName: "New York", mcd: true },
  37: { stateAbbr: "NC", stateName: "North Carolina", mcd: false },
  38: { stateAbbr: "ND", stateName: "North Dakota", mcd: false },
  39: { stateAbbr: "OH", stateName: "Ohio", mcd: false },
  40: { stateAbbr: "OK", stateName: "Oklahoma", mcd: false },
  41: { stateAbbr: "OR", stateName: "Oregon", mcd: false },
  42: { stateAbbr: "PA", stateName: "Pennsylvania", mcd: true },
  44: { stateAbbr: "RI", stateName: "Rhode Island", mcd: true },
  45: { stateAbbr: "SC", stateName: "South Carolina", mcd: false },
  46: { stateAbbr: "SD", stateName: "South Dakota", mcd: false },
  47: { stateAbbr: "TN", stateName: "Tennessee", mcd: false },
  48: { stateAbbr: "TX", stateName: "Texas", mcd: false },
  49: { stateAbbr: "UT", stateName: "Utah", mcd: false },
  50: { stateAbbr: "VT", stateName: "Vermont", mcd: true },
  51: { stateAbbr: "VA", stateName: "Virginia", mcd: false },
  53: { stateAbbr: "WA", stateName: "Washington", mcd: false },
  54: { stateAbbr: "WV", stateName: "West Virginia", mcd: false },
  55: { stateAbbr: "WI", stateName: "Wisconsin", mcd: true },
  56: { stateAbbr: "WY", stateName: "Wyoming", mcd: false },
};
